# Generated by Django 3.1.2 on 2020-10-31 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='streamname',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Stream'),
        ),
    ]
