# Generated by Django 3.1.2 on 2020-11-01 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20201031_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collegesofcourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collegename', models.CharField(max_length=100)),
                ('courseid', models.ForeignKey(db_column='courseid', on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.course')),
            ],
            options={
                'db_table': 'collegesofcourse',
                'managed': True,
            },
        ),
        migrations.DeleteModel(
            name='CollegeCourse',
        ),
    ]
