# Generated by Django 3.1.2 on 2020-11-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201101_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
