# Generated by Django 3.1.2 on 2020-11-02 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_delete_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistWishlistitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('item', models.ForeignKey(db_column='collegeid', on_delete=django.db.models.deletion.DO_NOTHING, to='quiz.college')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'db_table': 'wishlist_wishlistitem',
                'managed': True,
            },
        ),
    ]
