# Generated by Django 3.1.2 on 2020-11-02 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_wishlistwishlistitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistwishlistitem',
            name='item',
            field=models.IntegerField(),
        ),
    ]
