# Generated by Django 3.1.2 on 2020-11-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_remove_college_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='item',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='user',
            field=models.CharField(max_length=30),
        ),
    ]
