# Generated by Django 3.1.2 on 2020-11-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0012_auto_20201103_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneConsult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'phone_consult',
                'managed': False,
            },
        ),
    ]
