# Generated by Django 3.1.2 on 2020-11-04 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_auto_20201104_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='rating',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
