# Generated by Django 3.1.2 on 2020-11-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_college_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegesofcourse',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='collegesofcourse',
            name='site',
        ),
    ]
